version: "3"

services:
  apigateway-svc:
    image: azureiotpcs/simulation-api-gateway:millennium
    ports:
      - "443:443"
    depends_on:
      - webui-svc
      - devicesimulation-svc
    volumes:
      - /app/certs:/app/certs:ro

  webui-svc:
    image: azureiotpcs/device-simulation-webui:millennium
    depends_on:
      - devicesimulation-svc
    volumes:
      - /app/webui-config.js:/app/build/webui-config.js:ro

  devicesimulation-svc:
    image: azureiotpcs/device-simulation-dotnet:millennium
    depends_on:
      - storageadapter-svc
    environment:
      - PCS_LOG_LEVEL
      - PCS_IOTHUB_CONNSTRING=none
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter-svc:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_SUBSCRIPTION_DOMAIN
      - PCS_SUBSCRIPTION_ID
      - PCS_RESOURCE_GROUP
      - PCS_IOHUB_NAME
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.core.somaxconn=1024
    # ----------------------------------------------------------------------------
    #
    # How to mount custom device models.
    #
    # The path depends on the Docker Compose version, see first line in this file.
    # With Docker Compose v2, you must specify an absolute path, i.e starting with "/".
    # With Docker Compose v2, you can specify either an absolute of relative path.
    #
    #   1. Upload your device models in the path specified
    #   2. Uncomment the lines below, using either a relative or absolute path.
    #   3. Restart the services.
    #volumes:
    #  - /absolute-path/my-device-models:/app/data:ro
    #  - ./relative-path-my-device-models:/app/data:ro
    #
    # ----------------------------------------------------------------------------
    #
    # How to mount a custom configuration file in the single VM.
    #
    #   1. Edit /app/device-simulation-appsettings.ini
    #   2. Uncomment the next two lines and restart the services.
    #volumes:
    #  - /app/device-simulation-appsettings.ini:/app/webservice/appsettings.ini:ro
    # ----------------------------------------------------------------------------

  storageadapter-svc:
    image: azureiotpcs/pcs-storage-adapter-dotnet:millennium
    environment:
      - PCS_LOG_LEVEL
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
